### ISSUE TITLE
[Proto, Hamevo, Docs] Make `HamEvo` the central operations in Qadence

### ISSUE THREAD

**Issue by madagra** [pasqal-io/qadence#127]
Description to be filled.

**Comment by Roland-djee** [comment]
@jpmoutinho Is this relevant/already the case ?

**Comment by jpmoutinho** [comment]
This is a bit of an exploratory idea, but we can keep it in mind for the future. The goal would be to _always_ describe operations (in the docs) in terms of their hamiltonian evolution, even if just simple digital gates like CNOT or RX or anything else. The goal would be to instruct users on this equivalence and then make the introduction of "analog" operations more natural, since it is just a generalization.

**Comment by Roland-djee** [comment]
> This is a bit of an exploratory idea, but we can keep it in mind for the future. The goal would be to _always_ describe operations (in the docs) in terms of their hamiltonian evolution, even if just simple digital gates like CNOT or RX or anything else. The goal would be to instruct users on this equivalence and then make the introduction of "analog" operations more natural, since it is just a generalization.

OK thanks makes sense.

**Comment by jpmoutinho** [comment]
Closing as no longer relevant
