### ISSUE TITLE
[Refactoring, DA, Backends, Hamevo] Optimize block_to_tensor calls for repeated execution of HamEvo

### ISSUE THREAD

**Issue by dominikandreasseitz** [pasqal-io/qadence#134]
right now, we call block_to_tensor in every forward pass to get the hamiltonian, which is then exponentiated in native pyq. lets find a way to not have to call block_to_tensor but rather "fill in" parameter values in a smarter way.

**Comment by madagra** [comment]
@dominikandreasseitz I assume this is for parametrized generators, right? How would you "fill in" the parameters, though? It seems pretty hard to single out the places in the Hamiltonian matrix that are affected by different parameters in the abstract representation.

**Comment by dominikandreasseitz** [comment]
@madagra yes, exactly, i am referring to the case when we have a parametrized generator. youre right i guess however i think the block_to_tensor calls are quite expensive. so thats why i wanted to just put it on the table for discussion

**Comment by jpmoutinho** [comment]
This would essentially imply running a symbolic block_to_tensor, computing the kronecker product of all the symbolic matrices to get the larger matrix. Assuming this could be done somewhat efficiently and stored in memory such that updating the parameter values would be mostly "free", it could potentially speed up the forward pass. However, the biggest bottleneck will always be running matrix_exp at each forward pass (assuming non-diagonal hamiltonians) and that would not change, so I think it is unlikely that any speedup coming from this would be noticeable past a certain number of qubits. Maybe for diagonal hamiltonians it would make more sense (since the block_to_tensor there is also more efficient).

**Comment by Roland-djee** [comment]
@jpmoutinho @dominikandreasseitz Relevant ?

**Comment by dominikandreasseitz** [comment]
relevant but would need some proper thinking/planning

**Comment by jpmoutinho** [comment]
Closing after moving to PyQTorch: https://github.com/pasqal-io/pyqtorch/issues/176
