### ISSUE TITLE
[Documentation] Installation instructions: mention OS, tips for Windows/Linux/MacOS ?

### ISSUE THREAD

**Issue by vincentelfving** [pasqal-io/qadence#160]
After discussing with some of the recent users of qadence, I realized we are not yet mentioning any specifics on installation. It is assumed that the user has Linux or MacOS running and then everything will be fine (I think). For GraphViz there are specific instructions for Ubuntu and MacOS.

Suggestion: Let's add an explanation in the README/documentation, which states that we have tested and support Linux and MacOS currently, and that we recommend either WSL2 or dual-booting for those running Windows. We could add a link to a trusted/clear WSL2 installation guide or a super short intro to it. What do you think?

**Comment by madagra** [comment]
Those instructions are actually already available: https://pasqal-io.github.io/qadence/v1.0.4/#installation-guide. Normally, this kind of instruction should not be mentioned in the code documentation (since they are very much user/system dependent even if you have the same operating system) but adding a link to a good WSL guide + being more explicit is a good idea.

**Comment by Roland-djee** [comment]
Moving to backlog.

**Comment by mlahariya** [comment]
Worth investigating. Install on different platforms and document behaviors. 
We can close if everything works fine. @RolandMacDoland
